extra-keys = [ \
    ['ESC', 'TAB', {key: KEYBOARD, display: '⌨'}, {macro: '\u001b[5~', display: 'PGUP'}, '/', {key: UP, display: '↑'}, {key: BACKSPACE, display: '⌫'}, {macro: '\u001b[2~', display: 'INS'}, {key: HOME, display: 'home'}], \
    ['CTRL', 'ALT', {key: SHIFT, display: '⇧'}, {macro: '\u001b[6~', display: 'PGDN'}, {key: LEFT, display: '←'}, {key: DOWN, display: '↓'}, {key: RIGHT, display: '→'}, {macro: '\u001b[4~', display: 'END'}, 'ENTER'] \
]

allow-external-apps = true

fullscreen = true

# 不要在 Termux App 启动时自动弹出软键盘（避免启动开屏动画期间发生 Resize/挤压导致花屏）
hide-soft-keyboard-on-startup = true

# 若发现键盘遮挡终端内容，再改回 true。
use-fullscreen-workaround = false

# Open a new terminal with ctrl + t (volume down + t)
shortcut.create-session = ctrl + t

# Go one session down with (for example) ctrl + 2
shortcut.next-session = ctrl + 2

# Go one session up with (for example) ctrl + 1
shortcut.previous-session = ctrl + 1

# Rename a session with (for example) ctrl + n
shortcut.rename-session = ctrl + u

# Beep with a sound.
# bell-character=beep

# Cursor Blinking
terminal-cursor-blink-rate=600

# Remove horizontal margins so extra-keys span the full screen width
terminal-margin-horizontal=0
terminal-margin-vertical=0

# 蓝牙键盘打字能触发拼音候选
enforce-char-based-input = true

# 确保音量键调节系统音量
volume-keys = volume
